import { QueryProvider } from '@/providers/query-provider';
import './global.css';
import '@aibox/ui/index.css';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <QueryProvider>
        <body>
          <main>{children}</main>
        </body>
      </QueryProvider>
    </html>
  );
}
