import './global.css';
import '@aibox/ui/index.css';
import { ReactNode } from 'react';
import { dehydrate } from '@tanstack/react-query';
import QueryProvider, { createQueryClient } from '@/providers/queryProvider';
import { Notifications } from '@/components/notification/Notifications';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const serverQueryClient = createQueryClient();
  const dehydratedState = dehydrate(serverQueryClient);

  return (
    <html lang="en">
      <body>
        <QueryProvider dehydratedState={dehydratedState}>
          {children}
          <Notifications />
        </QueryProvider>
      </body>
    </html>
  );
}
