import './global.css';
import '@aibox/ui/index.css';

import { Header } from '@/components/header';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
