const strings = {
  cancel: 'انصراف',
  approve: 'تأیید',
  description: 'توضیحات',
  titleIsRequired: 'عنوان اجباری‌ است',
  descriptionIsRequired: 'توضیحات اجباری‌ است',
  areYouSure: 'آیا مطمئن هستید؟',
  deprecateHintMessage:
    'پس از انقضا، استفاده از این نسخه برای کاربران ممکن نیست.',
  deprecateAPI: 'منقضی کردن نسخه',
  willShowInApiMarkert: 'با تأیید کردن، API در مارکت منتشر خواهد شد.',
  rejectAPI: 'مردود کردن API',
  approveApi: 'تأیید کردن API',
  reportResloveError: 'گزارش رفع مشکل',
  rejectTitle: 'عنوان پیام به ارائه دهنده',
  additionalDescription: 'توضیحات بیشتر را وارد کنید.',
  apisList: 'لیست APIها',
  reports: 'گزارش‌ها',
  waitingForAccept: 'در انتظار تأیید',
  deprecating: 'درحال منقضی شدن',
  deprecated: 'منقضی شده',
  approved: 'تأیید شده',
  incomplete: 'ناقص',
  rejected: 'مردود',
  serviceError: 'خطای سرویس',
  apiName: 'نام API',
  provider: 'ارائه دهنده',
  version: 'ورژن',
  usersCount: 'تعداد کاربران',
  requestsCount: 'تعداد فراخوانی',
  totalRequestsCount: 'مجموع فراخوانی‌ها',
  status: 'وضعیت',
  tableActions: 'عملیات',
  approvedDate: 'تاریخ کسب تأییدیه',
  userName: 'نام کاربر',
  resolveApiError:
    'با زدن دکمه «تأیید»، به تمامی استفاده کنندگان سرویس شما، رفع مشکل سرویس اطلاع داده خواهد شد.',
  apiCount: 'تعداد APIها',
  earningProfit: 'اعتبار کسب شده (تومان)',
  avrageLatencyMs: 'میانگین تأخیر(ms)',
  avrageSatisfaction: 'میانگین رضایت کاربران',
  registerDate: 'زمان ثبت نام',
  notAnsweredTicket: 'تیکت در انتظار پاسخ',
  view: 'مشاهده',
  inGpuQueue: 'کاربر در صف رایانش گرافیکی',
  inApiQueue: 'کاربر در صف استفاده از API',
  hourly: 'ساعتی',
  week: 'هفته',
  weekly: 'هفتگی',
  month: 'ماه',
  monthly: 'ماهانه',
  year: 'سال',
  yearly: 'سالانه',
  newUsers: 'کاربران جدید',
  increase: 'رشد',
  decrease: 'کاهش',
  production: 'پروداکشن',
  zanjan: 'زنجان',
  activeUsers: 'کاربران فعال',
  totalUsers: 'کل کاربران',
  gpuComputing: 'رایانش گرافیکی',
  platform: 'پلتفرم',
  apiMarket: 'API مارکت',
  common: 'مشترک',
  user: 'کاربر',
  compareToLastMonth: 'نسبت به ماه گذشته',
  gpuComputingUsers: 'کاربران رایانش گرافیکی',
  platformUsers: 'کاربران پلتفرم',
  apiMarketUsers: 'کاربران API مارکت',
  commonUsers: 'کاربران مشترک',
  remainCharge: 'باقی مانده شارژ',
  usedApi: 'استفاده از api',
  withDrawCharge: 'برداشت شده',
  incomes: 'درآمدها',
  totalIncome: 'مجموع درآمدها',
  toman: 'تومان',
  remainingUserCharges: 'باقیمانده شارژ حساب کاربران',
  providersWithDraw: 'سهم برداشت شده از ارائه‌دهندگان',
  apiPlatform: 'پلتفرم ارائه API',
  totalVersions: 'کل ورژن‌ها از ابتدا',
  inQueueUsers: 'کاربران در صف',
  usersCurrentlyUsing: 'کاربران درحال استفاده',
  totalApis: 'کل APIها',
  mostUsedApis: 'APIهای پرتقاضا',
  mostSellerApis: 'APIهای پردرآمد',
  usersCurrentlyComputing: 'کاربران درحال پردازش',
  avarageUseHours: 'میانگین زمان استفاده (ساعت)',
  mostUseGpu: 'GPUهای پرتقاضا',
  tickets: 'تیکت‌ها',
  ticket: 'تیکت‌',
  addNewFactor: 'افزودن فاکتور جدید',
  price: 'مبلغ',
  priceToToman: 'مبلغ به تومان',
  discount: 'تخفیف',
  percentageDiscount: 'تخفیف به درصد',
  department: 'دپارتمان',
  createdDate: 'تاریخ ایجاد',
  dueDate: 'تاریخ سررسید',
  submit: 'ثبت',
  cancelAction: 'لغو عملیات',
  deleteModalDecription:
    'با حذف این مورد، امکان دسترسی به آن دیگر وجود نخواهد داشت.',
  deleteModalText: 'با پاک کردن این مورد،  تمامی اطلاعات آن از بین خواهد رفت.',
  deleteButtonText: 'حذف کردن',
  factors: 'فاکتورها',
  done: 'پرداخت شده',
  expired: 'منقضی',
  fail: 'پرداخت ناموفق',
  awaitingPayment: 'در انتظار پرداخت',
  num: 'شماره',
  discountColumn: 'تخفیف(٪)',
  priceColumn: 'مبلغ(تومان)',
  giftCode: 'کد هدیه',
  amountValue: 'مقدار اعتبار',
  tomanAmountValue: 'مقدار اعتبار به تومان',
  expiredDate: 'تاریخ انقضاء',
  totalCapacity: 'تعداد کل ظرفیت',
  usedCapacity: 'تعداد استفاده شده',
  remainingCapacity: 'ظرفیت باقی‌مانده',
  loginToYourAccount: 'ورود به حساب کاربری',
  phoneOrEmail: 'شماره موبایل/ایمیل*',
  password: 'کلمه عبور',
  login: 'ورود',
  forgetPassword: 'فراموشی کلمه عبور',
  emails: 'ایمیل‌ها',
  sms: 'پیامک‌ها',
  notifications: 'اعلان‌ها',
  public_messages: 'پیام‌های همگانی',
  add_new_public_message: 'افزودن پیام همگانی جدید',
  edit_new_public_message: 'ویرایش پیام همگانی',
  add_new_default_message: 'افزودن متن پیش فرض جدید',
  edit_new_default_message: 'ویرایش متن پیش فرض',
  add_new_email_message: 'افزودن ایمیل جدید',
  edit_email_message: 'ویرایش ایمیل',
  add_new_sms_message: 'افزودن پیامک جدید',
  edit_new_sms: 'ویرایش پیامک',
  add_new_notif_message: 'افزودن اعلان جدید',
  edit_notif_message: 'ویرایش اعلان',
  default_message: 'متن پیش فرض',
  fourHundred: 'تا ۴۰۰ کاراکتر',
  twoHundred: 'تا ۲۱۰ کاراکتر',
  fiveThousand: 'تا ۵۰۰۰ کاراکتر',
  all: 'همه',
  general: 'عمومی',
  accounting: 'مالی',
  advertising: 'تبلیغاتی',
  invite: 'دعوت نامه',
  recivers: 'دریافت کنندگان *',
  selectRecivers: 'انتخاب دریافت کننده',
  messageSubject: 'موضوع پیام *',
  categoryName: 'نام دسته‌بندی',
  addCategory: 'افزودن دسته‌بندی جدید',
  editCategory: 'ویرایش دسته‌بندی',
  notifMessageSubject: 'نام اعلان گروهی',
  emailSubject: 'موضوع ایمیل (Subject)*',
  notifSubject: 'موضوع اعلان*',
  smsGroupName: 'نام پیامک گروهی',
  notifGroupName: 'نام اعلان گروهی',
  generalMessage: 'پیام گروهی',
  smsMessageName: 'نام پیامک گروهی',
  generalMessageText: 'نام پیام گروهی',
  notifMessageName: 'موضوع اعلان',
  emailGroupName: 'نام ایمیل گروهی',
  sendDateTo: 'تاریخ ارسال تا *',
  sendDateFrom: 'تاریخ ارسال از *',
  sendDate: 'تاریخ ارسال*',
  sendTimeTo: 'ساعت ارسال تا',
  sendTimeFrom: 'ساعت ارسال از',
  sendTime: 'ساعت ارسال ',
  category: 'دسته‌بندی',
  selectCategory: 'انتخاب دسته‌بندی',
  assign_ticket: 'تخصیص تیکت',
  choose_operator: 'انتخاب اپراتور',
  cancel_operation: 'لغو عملیات',
  versionFa: 'نسخه',
  choose_version: 'انتخاب نسخه',
  add_user: 'اضافه کردن کاربر',
  choose_user: 'انتخاب کاربر*',
  choose_category: 'انتخاب دسته‌بندی',
  priority: 'اولویت',
  choose_priority: 'انتخاب اولویت',
  subject: 'عنوان درخواست',
  input_text: 'متن ورودی',
  add_new_ticket: 'افزودن تیکت جدید',
  close_ticket: 'بستن تیکت',
  close_ticket_description: 'با بستن تیکت، امکان گفتگو از بین خواهد رفت.',
  close_ticket_title: 'آیا مطمئن هستید؟',
  loadingFaq: 'در حال بارگذاری سؤالات متداول...',
  updating: 'در حال بروزرسانی...',
  showing: 'در حال نمایش',
  scheduledToSend: 'برنامه‌ریزی شده جهت ارسال',
  sent: 'ارسال شده',
  unsuccessful: 'ناموفق',
  destination: 'مقصد',
  sendTimeRange: 'بازه ارسال',
  messageText: 'متن پیام',
  message: 'پیام',
  generalMessages: 'پیام‌های همگانی',
  emailMessages: 'لیست ایمیل‌ها',
  smsMessages: 'لیست پیامک‌ها',
  notifMessages: 'لیست اعلان‌ها',
  answerQuestions: 'به موارد زیر پاسخ دهید',
  low: 'کم',
  up: 'بالا',
  down: 'پایین',
  high: 'زیاد',
  medium: 'متوسط',
  users: 'کاربران',
  addUser: 'افزودن کاربر جدید',
  email: 'ایمیل*',
  accessLevel: 'سطح دسترسی',
  assignToMe: 'تخصیص به خود',
  assignToOthers: 'تخصیص به دیگران',
  opened: 'باز',
  user_answer: 'در انتظار پاسخ کاربر',
  admin_answer: 'در انتظار پاسخ شما',
  closed: 'بسته',
  requestId: 'شماره درخواست',
  operator: 'اپراتور',
  planType: 'نوع پلن',
  request: 'فراخوانی',
  activatedDate: 'تاریخ فعال‌سازی',
  activatedTime: 'زمان فعال‌سازی',
  maxDailyRequest: 'فراخوانی روزانه (بیشینه)',
  maxMonthlyRequest: 'فراخوانی ماهانه (بیشینه)',
  remainingTime: 'زمان باقی‌مانده',
  day: 'روز',
  remainingMonthlyRequest: 'تعداد فراخوانی ماهانه باقی‌مانده',
  remainingDailyRequest: 'تعداد فراخوانی روزانه باقی‌مانده',
  packageExpireDate: 'تاریخ اتمام بسته',
  totalRequestCall: 'تعداد فراخوانی انجام شده',
  totalComputingTime: 'زمان پردازش شده',
  serverDefaultUsage: 'میزان استفاده پیش‌فرض از سرور',
  inNormalMode: 'در حالت عادی',
  whileError: 'در هنگام بروز خطا',
  freeUseTime: 'زمان استفاده رایگان',
  hour: 'ساعت',
  to: 'تا',
  useCapacity: 'حجم مصرف شده',
  providerProfit: 'سهم ارائه‌ دهنده',
  platformProfit: 'سهم پلتفرم',
  changeProviderProfit: 'تغییر سهم ارائه‌ دهنده',
  ignore: 'لغو',
  admin: 'ادمین',
  changeAccessLevel: 'تغییر سطح دسترسی',
  active: 'فعال',
  deactive: 'غیرفعال',
  userStatus: 'وضعیت کاربر',
  changeUserStatus: 'تغییر وضعیت کاربر',
  userInfo: 'مشخصات کاربری',
  apiPackages: 'بسته‌های API',
  gpuPackages: 'بسته‌های GPU',
  myApi: 'APIهای ارائه شده',
  finance: 'امور مالی',
  setting: 'تنظیمات',
  token: 'توکن',
  nickName: 'نام مستعار',
  registerationDate: 'تاریخ عضویت',
  lastLogin: 'آخرین دسترسی',
  access: 'دسترسی',
  domain: 'سامانه',
  earned: 'اعتبار کسب شده',
  withdraw_amount: 'اعتبار قابل برداشت',
  remain_charge: 'اعتبار باقی مانده',
  submit_transaction: 'ثبت تراکنش',
  transaction_status: 'وضعیت تراکنش:',
  transaction_kind: 'نوع تراکنش:',
  transaction_id: 'شماره تراکنش',
  editTransaction: 'ویرایش تراکنش',
  deposit: 'واریز',
  withdraw: 'برداشت',
  canceled: 'لغو شده',
  inprogress: 'در حال اقدام',
  successful: 'موفق',
  TomanPrice: 'مبلغ (تومان)',
  date: 'زمان',
  title: 'عنوان',
  transactionType: 'نوع تراکنش',
  depositCharge: 'افزایش اعتبار',
  withdrawCharge: 'برداشت اعتبار',
  factor: 'فاکتور',
  package: 'پکیج',
  wage: 'دستمزد',
  buyApi: 'خرید API',
  saleApi: 'فروش API',
  compute: 'محاسبه',
  deactivedPhoneNumber: 'شماره موبایل کاربر فعال نشده است.',
  notRegisteredPhoneNumber: 'شماره موبایل کاربر ثبت نشده است.',
  resendActivationEmail: 'ارسال مجدد ایمیل فعالسازی',
  deacitvedEmail: 'ایمیل کاربر فعال نشده است.',
  has: 'دارد',
  doestNotHave: 'ندارد',
  apiPackage: 'بسته API',
  gpuPackage: 'بسته GPU',
  registeredApi: 'API ثبت شده',
  notRegistered: 'ثبت نشده',
  editUserAccountInfo: 'ویرایش اطلاعات حساب کاربری',
  editAccount: 'ویرایش اطلاعات',
  sumbitChanges: 'ثبت تغییرات',
  editInfo: 'ویرایش مشخصات',
  firstName: 'نام',
  lastName: 'نام خانوادگی',
  phoneNumber: 'شماره موبایل',
  gender: 'جنسیت',
  newsSummary: 'خلاصه خبر',
  edit: 'ویرایش',
  addNewsTitle: 'افزودن خبر جدید',
  editNews: 'ویرایش خبر',
  news: 'اخبار',
  publishDate: 'تاریخ انتشار',
  tags: 'تگ‌ها',
  thumbnail: 'تصویر شاخص (thumbnail)',
  addressSuffix: 'پسوند آدرس (slug)',
  newsContent: 'شرح اخبار',
  selectOption: 'انتخاب کنید',
  gpus: 'GPUها',
  model: 'مدل',
  ram: 'رم',
  brand: 'برند',
  codaCore: 'تعداد هسته Cuda',
  freeHours: 'ساعت استفاده رایگان',
  freeDays: 'بازه استفاده رایگان (روز)',
  motherboards: 'مادربردها',
  cores: 'تعداد هسته',
  motherboard: 'مادربرد',
  hourlyPrice: 'قیمت ساعتی',
  tomanHourlyPrice: 'قیمت ساعتی (تومان)',
  monthlyPrice: 'قیمت ماهانه',
  tomanMonthlyPrice: 'قیمت ماهانه (تومان)',
  hourlyDiscount: 'تخفیف ساعتی',
  percentageHourlyDiscount: 'تخفیف ساعتی (%)',
  monthlyDiscount: 'تخفیف ماهانه',
  percentageMonthlyDiscount: 'تخفیف ماهانه (%)',
  hourlyUsagePrice: 'قیمت استفاده ساعتی',
  monthlyUsagePrice: 'قیمت استفاده ماهانه',
  name: 'نام',
  capacity: 'حجم (GB)',
  configuration: 'پیکربندی',
  editConfiguration: 'ویرایش پیکربندی',
  addConfiguration: 'ایجاد پیکربندی',
  duplicateConfiguration: 'ایجاد پیکربندی مشابه',
  deleteConfiguration:
    'با پاک کردن این مورد تمامی اطلاعات آن‌ از بین خواهد رفت.',
  remove: 'پاک کردن ',
  chooseBrand: 'برند را انتخاب کنید',
  choosePackageType: 'نوع بسته را انتخاب کنید',
  discountPercent: 'درصد تخفیف',
  usage: 'میزان استفاده',
  packageStatus: 'وضعیت بسته',
  packageName: 'نام بسته',
  processor: 'پردازنده',
  startTime: 'زمان شروع',
  finishReserve: 'زمان اتمام رزرو',
  server: 'سرور',
  servers: 'سرورها',
  problems: 'مشکلات',
  downServer: 'پایین آوردن سرور',
  seeLogs: 'مشاهده لاگ',
  downSeverDescription: (email: string) =>
    `با پایین آوردن سرور، دسترسی ${email} به سرور پردازشی از بین خواهد رفت.`,
  createDate: 'زمان ایجاد',
  errorMessage: 'متن خطا',
  modelName: 'نام مدل',
  totalCount: 'تعداد کل',
  freeCount: 'تعداد آزاد',
  modelInfo: 'اطلاعات مدل',
  models: 'مدل‌ها',
  podName: 'نام pod',
  nodeName: 'نام node',
  nodes: 'nodeها',
  editFactor: 'ویرایش فاکتور',
  submitChanges: 'ثبت تغییرات',
  addNewGiftCode: 'افزودن کد هدیه جدید',
  codeTitle: 'عنوان کد',
  editGiftCode: 'ویرایش کد هدیه',
  deleteModalDescription:
    'با حذف کد هدیه، امکان دسترسی به آن دیگر وجود نخواهد داشت.',
  delete: 'حذف کردن',
  transactions: 'تراکنش‌ها',
  actions: 'عملیات',
  createNewTransaction: 'ایجاد تراکنش جدید',
  amount: 'مبلغ',
  amountToToman: 'مبلغ به تومان',
  creditDeposit: 'افزایش اعتبار',
  creditWithdraw: 'برداشت اعتبار',
  buyAPI: 'خرید API',
  saleAPI: 'فروش API',
  inProgress: 'در حال اقدام',
  failed: 'ناموفق',
  time: 'زمان',
  tomanAmount: 'مبلغ(تومان)',
  submitTransaction: 'ثبت تراکنش',
  failedTransaction: 'تراکنش ناموفق',
  successfulTransaction: 'تراکنش موفق',
  transactionNum: 'شماره تراکنش',
  confirm: 'تأیید',
  placeholderText: 'متن راهنما پیش‌فرض',
  transactionStatus: 'وضعیت تراکنش',
  inAwaitAction: 'در انتظار اقدام',
  deleteDescription: 'با حذف این مورد تمامی اطلاعات آن‌ از بین خواهد رفت.',
  newGpu: 'تعریف GPU جدید',
  editGpu: 'ویرایش GPU',
  newMotherboard: 'تعریف مادربرد جدید',
  editMotherboard: 'ویرایش مادربرد',
  error: 'خطا',
  running: 'درحال اجرا',
  turnedOff: 'خاموش شده',
  pending: 'در انتظار آماده سازی',
  prepare: 'درحال آماده‌سازی',
  shutDownByAssign: 'خاموش شده بدلیل اساین شدن',
  shutDownByAdmin: 'خاموش شده توسط ادمین',
  yes: 'بله',
  no: 'خیر',
  startServerMSG: 'از روشن کردن سرور مطمئن هستید؟',
  shutdownServerMSG:
    'با خاموش کردن سرور امکان دسترسی به این سرور از بین خواهد رفت.',
  deployServer: 'بالا آوردن سرور',
  retryDeploy: 'دیپلوی مجدد',
  cancelProcess: 'لغو فرآیند',
  shutdownServer: 'پایین آوردن سرور',
  useGpu: 'استفاده از GPU',
  cpuUsageWithCore: 'cpu درخواستی (core)',
  ramUsageWithGB: 'ram درخواستی (GB)',
  cpuUsage: 'cpu درخواستی',
  ramUsage: 'ram درخواستی',
  urlPath: 'مسیر حافظه',
  pathName: 'اسم حافظه',
  subjectTitle: 'عنوان پیام را وارد کنید',
  subjectDescription: 'متن پیام را وارد کنید',
  createDefaultMessage: 'ایجاد متن پیشفرض',
  anyDefaultMessage: 'تاکنون متن پیش فرضی ثبت نشده است.',
  send: 'ارسال',
  optionalDescription: 'توضیحات (اختیاری)',
  sendFile: 'ارسال فایل',
  fileLimitation: 'حجم فایل نباید بیشتر از 10 مگابایت باشد!',
  allowedFileType: 'فقط فایل‌های PDF و تصویر (JPEG, PNG) مجاز هستند!',
  yourMessage: 'پیام خود را بنویسید...',
  closedByAdmin: 'تیکت توسط ادمین بسته شد.',
  pdfFile: 'PDF فایل',
  editTicketCategory: 'ویرایش دسته‌بندی تیکت',
  closing: 'در حال بستن...',
  sending: 'در حال ارسال...',
  assignedToMe: 'اختصاص داده شده به من',
  openTicket: 'تیکت‌های باز',
  attachedFile: 'فایل پیوست',
  createdBy: 'ایجاد شده توسط ',
  chatStart: 'برای شروع گفتگو، تیکتی را از لیست انتخاب کنید',
  ticketStatus: ' تیکت مورد نظر وجود ندارد یا حذف شده است',
  messageDeled: 'پیام با موفقیت حذف شد',
  collections: 'مجموعه‌ها',
  collectionName: 'نام مجموعه',
  lastEdit: 'آخرین ویرایش',
  showOrder: 'ترتیب نمایش',
  collectionInfo: 'اطلاعات مجموعه',
  seoInfo: 'اطلاعات سئو',
  collectionEnglishName: 'نام لاتین مجموعه',
  addNewCollection: 'افزودن مجموعه جدید',
  editCollection: 'ویرایش مجموعه ',
  submitCollectionInfo: 'ثبت اطلاعات مجموعه',
  collectionLatinName: 'نام لاتین مجموعه',
  sortBasedOn: 'مرتب‌سازی بر اساس',
  select: 'انتخاب کنید',
  rankForShow: 'رنک جهت نمایش',
  rankForShowInMarket: 'رنک جهت نمایش در مارکت',
  query: 'کوئری',
  image: 'تصویر',
  statusForShowInMarket: 'وضعیت (نمایش در مارکت)',
  submitCollectionInfoChanges: 'ثبت تغییرات اطلاعات مجموعه',
  metaDescription: 'Meta Description',
  metaKeywords: 'Meta Keywords',
  metaKeywordsPlaceholderText: 'کلمات کلیدی را با «,» از هم جدا کنید.',
  canonical: 'Canonical',
  robots: 'Robots',
  imageLink: 'لینک تصویر',
  submitSeoInfo: 'ثبت اطلاعات سئو',
  submitSeoInfoChanges: 'ثبت تغییرات اطلاعات سئو',
  createdTime: 'زمان ایجاد',
  requestsNum: 'تعداد درخواست‌ها',
  usersNum: 'تعداد کاربران',
  rate: 'امتیاز',
  earningAmount: 'میزان درآمد',
  packageType: 'نوع بسته',
  plan: 'پلن',
  stepPrice: 'قیمت پله‌ای',
  freePackage: 'پکیج رایگان',
  stepPackage: 'پکیج پله‌ای',
  payPerUsage: 'پرداخت به میزان استفاده',
  deleteLogDescriptionWithLogInfo: (apiName?: string, userName?: string) =>
    `با حذف کردن این مورد، بسته API «\u2066${apiName}\u2069» کاربر «\u2066${userName}\u2069» از بین خواهد رفت.`,
  deleteLogWithNumberDescription: (count: number) =>
    `شما ${count} مورد را انتخاب کرده‌اید، با حذف کردن این موارد تمامی بسته‌های API کاربران انتخاب شده از بین خواهد رفت.`,
  categories: 'دسته‌بندی‌ها',
  categoryInfo: 'اطلاعات دسته‌بندی',
  addNewCategory: 'افزودن دسته‌بندی جدید',
  return: 'بازگشت',
  addNewQuestion: 'افزودن سوال جدید',
  createMessage: 'افزودن پیام...',
  questions: 'سوالات',
  tokens_list: 'لیست توکن‌ها',
  deployment: 'Deployment',
  log: 'لاگ',
  logs: 'لاگ‌ها',
  logInfo: 'گزارش‌ بسته‌ها',
  apisQueue: 'صف APIها',
  errors: 'خطاها',
  deploymentName: 'نام Deployment',
  solved: 'حل شده',
  notSolved: 'حل نشده',
  approveBtnText: 'تأیید کردن',
  solveProblemModalDescription: 'آیا از برطرف شدن این مشکل اطمینان دارید؟',
  label: 'لیبل',
  scope: 'اسکوپ',
  inQueue: 'در صف',
  canceledByAdmin: 'لغو شده توسط ادمین',
  successfulCompletion: 'اتمام موفق',
  inPreparation: 'درحال آماده‌سازی',
  apiPark: 'پارک API',
  troubleshootingReport: 'گزارش رفع مشکل',
  errorDetails: 'جزئیات خطا',
  viewReports: 'مشاهده گزارشات',
  viewPage: 'مشاهده صفحه',
  defaultShareOfProvidersAndPlatformInMode:
    'سهم پیش فرض ارائه دهندگان و پلتفرم در حالت',
  dependent: 'وابسته',
  inDependent: 'مستقل',
  providerShare: 'سهم ارائه دهنده',
  platformShare: 'سهم پلتفرم',
  changeDefaultShare: 'تغییر سهم پیش‌فرض',
  testApiCallsNum: 'تعداد فراخوانی API تستی',
  changeCallNum: 'تغییر تعداد فراخوانی',
  userProcessingTimeWithoutCredit: 'ساعت پردازش کاربر بدون داشتن اعتبار',
  userProcessingLimitWithoutCredit: 'میزان پردازش کاربران بدون داشتن اعتبار',
  changeProcessingLimit: 'تغییر میزان پردازش',
  providerShareinMode: 'سهم ارائه‌دهنده در حالت',
  processingLimitAfterUserBalanceDepletion:
    'میزان پردازش پس از اتمام شارژ حساب کاربر',
  serviceProfitSplitInMode:
    'تقسیم سود سرویس‌ها بین ارائه‌دهنده و پلتفرم در حالت',
  freeTrialApiCallLimit: 'امکان فراخوانی API تا سقف مشخص به‌صورت تستی و رایگان',
  categoryLatinName: 'نام لاتین دسته‌‌‌بندی',
  submitCategoryInfoChanges: 'ثبت تغییرات اطلاعات دسته‌بندی',
  submitCategoryInfo: 'ثبت اطلاعات دسته‌بندی',
  jsonFormatText: 'فرمت ورودی باید json باشد.',
  usingGpu: 'استفاده از GPU',
  storageName: 'اسم حافظه',
  storagePath: 'مسیر حافظه',
  turnOff: 'خاموش کردن',
  turnOn: 'روشن کردن',
  stopServerHint:
    'با خاموش کردن سرور امکان دسترسی به این سرور از بین خواهد رفت.',
  startServerHint: 'از روشن کردن سرور مطمئن هستید؟',
  requestedCpu: 'cpu درخواستی (core)',
  requestedRam: 'ram درخواستی (GB)',
  financial: 'مالی',
  changeSetting: 'تغییر تنظیمات',
  applyChanges: 'اعمال تغییرات',
  minute: 'دقیقه',
  podLifespanTitle: 'حداقل طول عمر برای هر پاد (دقیقه)',
  podLifespanDescription:
    'تمامی سرویس ها حداقل به این مقدار در دسترس خواهند بود و پس از آن در صورتی که این منبع مورد نیاز باشد سرویس خاموش خواهد شد.',
  mostVisitedPeriodTitle: 'حداقل زمان بررسی الستیک',
  mostVisitedPeriodDescription:
    'حداقل چند روز قبل برای بررسی استفاده این سرویس از الستیک چک شود.',
  mostVisitedCntTitle:
    'حداقل تعداد تکرار لازم در الستیک برای پرتکرار در نظر گرفته شدن',
  mostVisitedCntDescription:
    'تعداد فراخوانی، که اگر در بازه مشخص شده در فیلد بالا انجام شده بود، سرویس محبوب شناخته شود.',
  minPriorityTitle:
    'حداقل تعداد درخواست لازم از یک api در صف برای تسریع دیپلوی',
  minPriorityDescription:
    'حداقل چند درخواست از یک سرویس در صف موجب آماده سازی سرویس می‌شود.',
  userDepositCyclesTitle: 'سیکل‌های واریز وجه به حساب کاربر',
  userDepositCyclesDescription: 'اطلاعات مربوط به سیکل‌های پرداخت به کاربران.',
  startAfterNDaysTitle: 'شروع پرداخت به کاربر بعد از چند روز کاری',
  userSelectableDaysTitle: 'تعداد روزهای قابل انتخاب توسط کاربر',
  firstDayAmountTitle: 'مقدار مبلغ قابل انتخاب توسط کاربر در روز اول',
  secondDayAmountTitle: 'مقدار مبلغ قابل انتخاب توسط کاربر در روز دوم',
  changeUserDepositCycleTitle: 'تغییر سیکل‌های وجه',
  notifPersianTitle: 'عنوان فارسی اعلان',
  notifLatinTitle: 'عنوان لاتین اعلان',
  showPriority: 'اولویت نمایش',
  showToUserStatus: 'وضعیت نمایش به کاربر',
  sendEmailByDefault: 'ارسال ایمیل به صورت پیش‌فرض',
  sendMessageByDefault: 'ارسال پیامک به صورت پیش‌فرض',
  editNotification: 'ویرایش اعلان',
  addNotification: 'افزودن اعلان',
  persianTitle: 'عنوان فارسی',
  latinTitle: 'عنوان لاتین',
  refuseChanges: 'لغو تغییرات',
  changePackage: 'تغییر بسته',
  show: 'نمایش',
  anErrorOccurred: 'مشکلی رخ داده است.',
  reloadPage: 'بارگذاری مجدد صفحه',
  viewDetails: 'مشاهده جزئیات',
  userCredit: 'اعتبار کاربر',
  tomanUserCredit: 'اعتبار کاربر(تومان)',
  giftCodeDetails: 'جزئیات کد هدیه',
  serviceUsers: 'افراد استفاده‌کننده',
  free: 'آزاد',
  inUse: 'درحال استفاده',
  retry: 'تلاش مجدد',
  exitQueueDesc: (email: string) =>
    `با خارج کردن صف، کاربر «${email}» از صف استفاده از رایانش گرافیکی خارج خواهد شد.`,
  chooseConfigPlaceholder: 'پیکربندی را انتخاب کنید.',
  chooseConfig: 'انتخاب پیکربندی',
  chooseDiskPlaceholder: 'دیسک را انتخاب کنید.',
  chooseDisk: 'انتخاب دیسک',
  choosePlanPlaceholder: 'پلن را انتخاب کنید.',
  choosePlan: 'انتخاب پلن',
  captchCode: 'کد امنیتی',
  removeFromQueue: 'خارج‌ کردن از صف',
  providedApi: 'APIهای ارائه شده',
  processing: 'ناقص',
  accepted: 'فعال',
  notAccepted: 'مردود',
  waitingDeprecate: 'در حال انقضا',
  waiting: 'درانتظار تأیید',
  proxyError: 'خطای سرویس',
  updatedDate: 'تاریخ کسب تأییدیه',
  requests: 'مجموع فراخوانی‌ها',
  enroll: 'تعداد کاربران',
  owner: 'نام API',
  isPublic: 'عمومی یا خصوصی',
  public: 'عمومی',
  private: 'خصوصی',
  disapproveSuccess: ' API مورد نظر با موفقیت مردود شد.',
  disapproveError: 'خطایی رخ داده است.',
  deprecateSuccess: ' API مورد نظر با موفقیت منقضی شد.',
  approveSuccess: ' API مورد نظر با موفقیت تأیید و در مارکت قرار گرفت.',
  proxyErrorDescription: 'گزارش خطا با موفقیت ثبت شد.',
  affiliate: 'واسطه‌گری',
  withdrawFromBankAccount: 'برداشت از حساب بانکی',
  amountTransfer: 'انتقال مبلغ',
  updateStatus: 'به‌روزرسانی وضعیت',
  others: 'سایر',
  storage: 'فضای ذخیره‌سازی',
  storageDashboardDescription: 'هزینه خرید فضای ذخیره‌سازی',
  aiServeices: 'سرویس‌های هوش مصنوعی',
  totalGpuComputing: 'مجموع پردازش ابری کاربران',
  aiServicesIncomeDescription: 'هزینه زیرساخت و سهم پلتفرم از سرویس‌ها',
  otherIncomeDashboardDescription: 'باقیمانده اعتبار کاربران، کد هدیه و ..',
  writtenText: 'متن نوشته شده..',
  averagePrecision: 'میانگین دقت',
  averageDelay: 'میانگین تاخیر',
  ratings: 'میزان رضایت',
  developedBy: 'توسعه داده شده توسط',
  lastUpdateAt: 'بروز رسانی شده است.',
  privacyAndPolicy: 'قوانین و شرایط استفاده',
  method: 'متد',
  accuracy: 'دقت',
  changeAccuracy: 'ویرایش دقت',
  delay: 'تاخیر',
  errorsCount: 'تعداد خطا',
  enpointsList: 'لیست Endpointها',
  inPrevWeek: 'در هفته گذشته',
  inPrevMonth: 'ماه گذشته',
  inPrevYear: 'درسال گذشته',
  validApiVersion: 'تعداد ورژن‌های مجاز برای API',
  neededValidApiForMarket: 'تعداد ورژن‌های مجاز برای حضور در API Market',
  providerCut: 'سهم ارائه‌دهنده (%)',
  platformCut: 'سهم پلتفرم (%)',
  submitInformation: 'ثبت اطلاعات',
  seoInfoUpdatedSuccessfully: 'اطلاعات سئو با موفقیت ویرایش شد',
  seoInfoAddedSuccessfully: 'اطلاعات سئو با موفقیت ثبت شد.',
  delayAmount: 'میزان تأخیر',
  total: 'مجموع',
  chart: 'نمودار',
  endpointName: 'نام Endpoint',
  response: 'پاسخ',
  modalApproveText:
    'با تأیید این امکان کاربران سایت قادر به تهیه این بسته خواهند بود.',
  modalDeprecateText:
    'پس از منقضی شدن، دیگر امکان استفاده از این نسخه برای کاربران وجود ندارد.',
  second: 'ثانیه',
  disapproveVersion: 'رد کردن ورژن',
  disapproveReason: 'دلیل رد کردن',
  versionExpiringSoon: 'این نسخه به زودی منقضی می‌شود.',
  upgradeResource: 'ارتقا منبع',
  deprecate: 'منقضی کردن',
  codeAddress: 'آدرس کد',
  portNumber: 'عدد پورت',
  key: 'کلید',
  resourceType: 'نوع منبع',
  approveAction: 'تأیید کردن',
  disapproveAction: 'رد کردن',
  resolveErrorSuccessMessage: 'گزارش رفع مشکل با موفقیت ثبت شد.',
  deactivePackage: 'بسته غیر فعال',
  pricePerCall: 'قیمت هر بار فراخوانی',
  daily: 'روزانه',
  maximumcallNumber: 'بیشینه تعداد فراخوانی',
  activatePackagePurchase: 'فعال کردن خرید بسته',
  deactivatePackagePurchase: 'غیرفعال کردن خرید بسته',
  number: 'عدد',
  yearlyCallCount: 'میزان فراخوانی (در هر سال)',
  callPrice: 'قیمت هر فراخوانی',
  tieredUsagePrice: 'قیمت استفاده پله‌ای',
  noCost: 'رایگان',
  from: 'از',
  validityPeriod: 'مدت اعتبار',
  oneYear: 'یک سال',
  activatePackageModalText:
    'با تأیید این امکان کاربران سایت قادر به تهیه این بسته خواهند بود.',
  deactivatePackageModalText:
    'با تأیید این امکان کاربران سایت قادر به تهیه این بسته نخواهند بود.',
  editFaq: 'ویرایش سؤالات متداول',
  addNewFaq: 'افزودن سؤالات متداول جدید',
  questionTitle: 'عنوان سوال',
  selectCategoryPlaceholder: 'دسته‌بندی را انتخاب کنید',
  answer: 'پاسخ',
  cancelOperation: 'لغو عملیات',
  loginWithUserToken: 'ورود با تو کن کاربر',
  comments: 'تعداد نظرات',
  userRatings: 'امتیاز کاربران',
  fullName: 'نام و نام خانوادگی',
  noData: 'اطلاعاتی موجود نیست.',
  proxyNoData:
    'باتوجه به نوع سرویس شما (پروکسی)، اطلاعاتی جهت نمایش وجود ندارد.',
  readMore: 'بیشتر بخوانید',
  collapse: 'جمع کردن',
  both: 'هردو',
  activating: 'در حال فعال سازی',
  monthlyPackageStatus: 'وضعیت بسته ماهانه',
  rejectUserPackageRequestDescription:
    'با مردود کردن، درخواست بسته کاربر لغو خواهد شد.',
  approveUserPackageDescription:
    'پس از تأیید، برای کاربر فاکتور صادر شده و بسته Gpu او فعال خواهد شد.',
  rejecting: 'مردود کردن',
  approving: 'تأیید کردن',
  reactivate: 'فعالسازی مجدد',
  volume: 'فضای ابری',
  volumes: 'فضاهای ابری',
  assignedCapacity: 'حجم تخصیص داده شده',
  volumesCount: 'تعداد فضاهای ابری',
  extendVolume: 'افزایش حجم',
  refreshVolume: 'آماده‌سازی مجدد',
  mountVolume: 'mount کردن',
  unmountVolume: 'unmount کردن',
  cloudStorage: 'فضای ابری',
  priceDescription: 'قیمت هر گیگابایت فضای ذخیره‌سازی برای خرید کاربر به تومان',
  defaultStorage: 'حجم پیش‌فرض',
  defaultStorageDescription: 'حافظه پیش‌فرض در سرور پردازشی',
  maximum_storage: 'حداکثر حجم',
  maximum_storage_description: 'بیشینه حجمی که کاربر می‌تواند خریداری کند.',
  recharge_factor_time: 'زمان صدور فاکتور تمدید',
  recharge_factor_time_description:
    'چند روز قبل از منقضی شدن فضای ذخیره‌سازی، برای کاربر فاکتور تمدید صادر شود.',
  delete_user_information_time: 'زمان حذف اطلاعات کاربر',
  delete_user_information_time_description:
    'چند روز بعد از منقضی شدن فضای ذخیره‌سازی، اطلاعات کاربر پاک شود.',
  latest_user_warning_message_time: 'زمان آخرین هشدار به کاربر',
  latest_user_warning_message_time_description:
    'زمان ارسال آخرین هشدار منقضی شدن حافظه ذخیره‌سازی به کاربر',
  not_found: 'صفحه مورد نظر شما یافت نشد.',
  home_page: 'خانه',
  systemMaintenanceTitle: 'سامانه درحال بهبود است',
  systemMaintenanceDescription:
    'متخصصین ما درحال بهبود و آماده‌سازی سامانه هستند، لطفاً کمی بعد مراجعه\n' +
    'نمایید.',
  networkErrorTitle: 'مشکلی رخ داده است.',
  networkErrorListTitle: 'جهت رفع مشکل موارد زیر را بررسی نمایید:',
  networkErrorCheckInternet: 'از اتصال خود به اینترنت اطمینان حاصل نمایید.',
  networkErrorReloadPage: 'صفحه را مجدداً بارگذاری نمایید.',
  networkErrorUseChrome: 'پیشنهاد می‌شود از مرورگر Chrome استفاده نمایید.',
  networkErrorRefreshPage:
    'در صورت رفع نشدن مشکل، چند دقیقه بعد مجدداً تلاش نمایید.',
  receiveExport: 'دریافت خروجی',
  informations: 'اطلاعات',
  exportType: 'نوع خروجی',
  asFilteredData: 'مطابق فیلتر جدول',
  allInformation: 'همه اطلاعات',
  paid: 'پرداخت شده',
  reserveFactor: 'صدور فاکتور جهت تمدید',
  connect: 'اتصال',
  paymnetType: 'نحوه پرداخت',
  dateTimePlaceHolder: 'تاریخ و زمان را انتخاب کنید',
  sendDatePlaceHolder: 'تاریخ و زمان ارسال را انتخاب کنید',
  dailyLimitPurchase: 'تعداد خرید بسته ساعتی در هر روز',
  dailyLimitPurchaseDescription:
    'کاربر در هر روز چند بار بتواند بسته ساعتی خود را تغییر دهد.',
  limitUsagePackage: 'زمان استفاده کاربر از بسته قبلی در صورت تغییر',
  limitUsagePackageDescription:
    'پس از حذف یا تغییر در پیکربندی بسته ساعتی از سمت ادمین، کاربر چند روز بتواند از بسته با  مشخصات قبلی خود استفاده کند.',
  youDontHaveAccessToThisSection: 'شما دسترسی به این بخش را ندارید.',
  expireDate: 'زمان اتمام بسته',
  mountPath: 'مسیر اتصال',
  manage_cloud_storage: 'رفتن به فضاهای ابری',
  cloud_capacity: 'حجم',
  isProxy: 'باتوجه به نوع سرویس (پروکسی)، اطلاعاتی جهت نمایش وجود ندارد.',
  cloudStorageNotConnectTitle: 'حافظه ابری متصل نشده است.',
  deleteGpuPackageModalDescription:
    'پس از حذف پیکربندی، کاربران امکان خرید این بسته را نخواهند داشت.همچنین به کاربران دارای این بسته هم مهلت استفاده داده خواهد شد.',
  submitConfigurationWarning:
    'با ویرایش اطلاعات، مشخصات بسته‌های رایانش گرافیکی تغییر خواهد کرد. کاربران دارای بسته نیز از تغییرات مطلع شده و مهلت استفاده با مشخصات قبلی خواهند داشت.',
  editSuccessMessage: 'ویرایش پیکربندی با موفقیت انجام شد.',
  deleteGpuPackageModalSuccess: 'حذف پیکربندی با موفقیت انجام شد.',
  showTickets: 'نمایش تیکت',
  serverStatus: 'وضعیت سرور',
  remainStorageCapacity: 'حجم باقی مانده',
  seeExtendVolumeFactor: 'مشاهده فاکتور افزایش حجم',
  seeReserveFactor: 'مشاهده فاکتور تمدید',
  seeFactor: 'مشاهده فاکتور',
  volumePath: 'مسیر ذخیره سازی',
  DeleteVolumeDate: 'زمان پاک شدن',
  assigneVolume: 'تخصیص داده شده',
  deleted: 'پاک شده',
  deleting: 'درحال پاک شدن',
  jupyterDefault: 'پیش فرض سرور پردازشی',
  connectVolume: 'اتصال فضای ابری',
  confirmDeleteVolume:
    'پس از حذف، تمامی اطلاعات فضای ذخیره‌سازی انتخابی بجز موارد پیش‌فرض آن حذف و غیر قابل دسترس خواهند بود.',
  connectVolumeDescription:
    'جهت اتصال، یکی از سرویس‌ها و یا سرور پردازشی خود را انتخاب کنید.',
  unmountVolumeDescription:
    'پس از جداسازی حافظه از سرویس مورد نظر، سرویس دیگر قادر به استفاده از محتویات حافظه نخواهد بود. پس از جداسازی، امکان اتصال به سایر سرویس‌ها و استفاده از محتویات آن فراهم است.',
  createVolume: 'ایجاد فضای ابری',
  createNewFactor: 'ایجاد فاکتور برای کاربر',
  paidFactor: 'پرداخت شده',
  paymentTypeDescription: 'توضیح روش پرداخت',
  expiredStatus: 'منقضی شده',
  readyStatus: 'درحال آماده سازی',
  stoppedStatus: 'متوقف شده',
  assignVolumeStatus: 'خاموش شده به دلیل اختصاص حافظه',
  startingStatus: 'در انتظار شروع',
  runningStatus: 'درحال استفاده',
  systemError: 'خطای سیستمی',
  adminStopped: 'خاموش شده توسط ادمین',
  adminCanceled: 'لغو شده توسط ادمین',
  and: 'و',
  minutes: 'دقیقه',
  remaining_days: 'زمان باقی‌مانده ماهانه',
  noPackage: 'بسته ای وجود ندارد',
  limitationMessage:
    'تغییر میزان استفاده پیش‌فرض از سرور پردازشی با موفقیت انجام شد.',
  paymentTypeDescriptions: 'توضیحات پرداخت',
  not_approved_message: 'پیام تأیید نشده',
  reported: 'گزارش شده',
  is_answered: 'پاسخ داده شده',
  wait_answer: 'در انتظار پاسخ',
  feedback: 'بازخوردها',
  contribute: 'مشارکت',
  backupReports: 'گزارش‌های پشتیبان گیری ',
  deactiveBackup:
    'پس از تأیید، دیگر نسخه پشتیبان از اطلاعات حافظه گرفته نخواهد شد.',
  activeBackup:
    'پس از تأیید، از اطلاعات حافظه بصورت دوره‌ای نسخه پشتیبان تهیه می‌شود.',
  initializing: 'درحال آماده سازی',
  approve_converse: 'تأیید گفت‌وگو',
  delete_converse: 'حذف پیام',
  search: 'جستجو کنید...',
  delete_converse_reason: 'گفتگو شما به دلیل مغایرت با قوانین سایت حذف شد.',
  delete_modal_desc: 'از حذف گفت‌وگو انتخاب شده اطمینان دارید؟',
  delete_converse_success: 'گفت‌وگو با موفقیت حذف شد.',
  delete_reason: 'علت حذف را بنویسید...',
  delete_conversation: 'حذف گفتگو',
  disapproved: 'تایید نشده',
  reply_count: 'تعداد پاسخ',
  like_count: 'تعداد لایک',
  dislike_count: 'تعداد دیسلایک',
  last_activity: 'آخرین فعالیت',
  secsAgo: 'چند لحظه پیش',
  minsAgo: 'دقیقه پیش',
  hoursAgo: 'ساعت پیش',
  daysAgo: 'روز پیش',
  monthsAgo: 'ماه پیش',
  yearsAgo: 'سال پیش',
  discussions: 'گفت‌وگوها',
  converse_approved: 'گفت‌وگو با موفقیت تأیید شد.',
  messages: 'پیام‌ها',
  dragOrSelectImage: 'برای انتخاب کلیک کنید و یا تصویر را در اینجا رها کنید.',
  jupyter: 'سرور پردازشی',
  limitUserAccess:
    'پس از تأیید، دسترسی کاربر در صفحه سرور پردازشی محدود خواهد شد.',
  cancelLimitUserAccess: 'لغو محدود کردن دسترسی کاربر',
  LimitUserAccess: 'محدود کردن دسترسی کاربر',
  approve_message: 'تأیید پیام',
  delete_message: 'حذف گفت‌وگو',
  serverIsRunning: 'سرور شما در حال اجرا است.',
  unmountWarning:
    'در صورت جداسازی، سرور شما متوقف و مجدداً راه‌اندازی خواهد شد.',
  noSubject: 'موردی یافت نشد.',
  worth: 'قیمت',
  searchIn: (args: string[]) => `جستجو در ${args.join('، ')}`,
};

export default strings;
