const strings = {
  cancel: 'انصراف',
  approve: 'تایید',
  description: 'توضیحات',
  titleIsRequired: 'عنوان اجباری‌ است',
  descriptionIsRequired: 'توضیحات اجباری‌ است',
  areYouSure: 'آیا مطمئن هستید؟',
  deprecateHintMessage:
    'پس از منقضی شدن، دیگر امکان استفاده از این نسخه برای کاربران وجود ندارد.',
  deprecateAPI: 'منقضی کردن API',
  willShowInApiMarkert: 'با تأیید کردن، API در مارکت منتشر خواهد شد.',
  rejectAPI: 'مردود کردن API',
  approveApi: 'تایید کردن API',
  reportResloveError: 'گزارش رفع مشکل',
  rejectTitle: 'عنوان پیام به ارائه دهنده',
  additionalDescription: 'توضیحات بیشتر را وارد کنید.',
  apisList: 'لیست APIها',
  reports: 'گزارش‌ها',
  waitingForAccept: 'در انتظار تایید',
  deprecating: 'درحال منقضی شدن',
  deprecated: 'منقضی شده',
  approved: 'تایید شده',
  incomplete: 'ناقص',
  rejected: 'مردود',
  serviceError: 'خطای سرویس',
  apiName: 'نام API',
  provider: 'ارائه دهنده',
  version: 'ورژن',
  usersCount: 'تعداد کاربران',
  requestsCount: 'تعداد فراخوانی',
  totalRequestsCount: 'مجموع فراخوانی‌ها',
  status: 'وضعیت',
  tableActions: 'عملیات',
  approvedDate: 'تاریخ کسب تأییدیه',
};

export default strings;
