export const userInfoStrings = {
  deactivedPhoneNumber: 'شماره موبایل کاربر فعال نشده است.',
  resendActivationEmail: 'ارسال مجدد ایمیل فعالسازی',
  deacitvedEmail: 'ایمیل کاربر فعال نشده است.',
  has: 'دارد',
  doestNotHave: 'ندارد',
  apiPackage: 'بسته API',
  gpuPackage: 'بسته GPU',
  registeredApi: 'API ثبت شده',
  notRegistered: 'ثبت نشده',
  editUserAccountInfo: 'ویرایش اطلاعات حساب کاربری',
  sumbitChanges: 'ثبت تغییرات',
  cancel: 'لغو',
  editInfo: 'ویرایش مشخصات',
  firstName: 'نام',
  lastName: 'نام خانوادگی',
  nickname: 'نام مستعار',
  email: 'ایمیل',
  phoneNumber: 'شماره موبایل',
  gender: 'جنسیت',
  status: 'وضعیت',
};
