export const TicketingString = {
  tickets: 'تیکت‌ها',
  assign_ticket: 'تخصیص تیکت',
  choose_operator: 'انتخاب اپراتور',
  cancel: 'انصراف',
  submit: 'ثبت',
  cancel_operation: 'لغو عملیات',
  version: 'نسخه',
  choose_version: 'انتخاب نسخه',
  add_user: 'اضافه کردن کاربر',
  choose_user: 'انتخاب کاربر*',
  category: 'دسته‌بندی*',
  choose_category: 'انتخاب دسته‌بندی',
  priority: 'اولویت*',
  choose_priority: 'انتخاب اولویت',
  subject: 'عنوان درخواست*',
  input_text: 'متن ورودی',
  add_new_ticket: 'افزودن تیکت جدید',
  close_ticket: 'بستن تیکت',
  close_ticket_description: 'با بستن تیکت، امکان گفتگو از بین خواهد رفت.',
  close_ticket_title: 'آیا مطمئن هستید؟',
};
