export const factorStrings = {
  addNewFactor: 'افزودن فاکتور جدید',
  user: 'کاربر',
  price: 'مبلغ',
  priceToToman: 'مبلغ به تومان',
  discount: 'تخفیف',
  percentageDiscount: 'تخفیف به درصد',
  department: 'دپارتمان',
  status: 'وضعیت',
  createdDate: 'تاریخ ایجاد',
  dueDate: 'تاریخ سررسید',
  description: 'توضیحات',
  submit: 'ثبت',
  cancelAction: 'لغو عملیات',
  deleteModalTitle: 'آیا مطمئن هستید؟',
  deleteModalDecription:
    'با حذف فاکتور، امکان دسترسی به آن دیگر وجود نخواهد داشت.',
  deleteButtonText: 'حذف کردن',
  factors: 'فاکتورها',
  done: 'پرداخت شده',
  expired: 'منقضی',
  fail: 'پرداخت ناموفق',
  inPorgress: 'در انتظار پرداخت',
  num: 'شماره',
  discountColumn: 'تخفیف(٪)',
  priceColumn: 'مبلغ(تومان)',
  refuse: 'انصراف',
  editFactor: 'ویرایش فاکتور',
  submitChanges: 'ثبت تغییرات',
  cancel: 'لغو',
};
